### ISSUE TITLE
Ability to write temporarily locked out: does not unlock after required RI threshold met and exceeded

### ISSUE THREAD

**Issue by beleagured** [twitter/communitynotes#346]
Feature: You are temporarily locked out form writing new notes
Problem: Unlock your ability to write
Will not unlock after requested Rating Impact increase met and exceeded:
Increase your Rating Impact to 2561, from your current score of 2598.

Locked out past RI requirement since 6/20, no response to mutliple DMs @communitynotes

![Image](https://github.com/user-attachments/assets/41465889-c1ee-47c5-99a6-ecd5b3fbb1fc)

Windows/Chrome web and Android mobile X app

**Comment by twitterbirdwatch** [comment]
Thank you for the report. This was due to a temporary outage of the system that updates Writing and Rating Impact scores. Was fixed as of yesterday. Let us know if you continue to see any issues.

**Comment by beleagured** [comment]
Issue persists. Logged out both devices, cleared cache and cookies.

![Image](https://github.com/user-attachments/assets/642b3282-98e4-46a2-8986-59a0baddcadf)

**Comment by beleagured** [comment]
Issue resolved.
